### ISSUE TITLE
White Page

### ISSUE THREAD

**Issue by Elfobog** [JimmyPun610/Plugin.XF.Controls#1]
Hello,
I copy the example pages of WebViewSample and its work with a all site but not with dbconfigurazioni.com ... with this site (which is the site that interests me) I see everything white, any ideas about it? What could be the problem?

**Comment by JimmyPun610** [comment]
Hi @Elfobog
I updated the version and you can try in new version 1.0.0.10.
I put below code in renderer and it seems fine now,
```
 webView.Settings.DomStorageEnabled = true;
``` 

FYI
https://stackoverflow.com/questions/14300664/android-webview-displaying-blank-page

**Comment by Elfobog** [comment]
where should i insert it?

**Comment by JimmyPun610** [comment]
Hi @Elfobog 
Please check below file
https://github.com/JimmyPun610/Plugin.XF.Controls/blob/master/Plugin.XF.Controls.Droid/Renderer/EnhancedWebViewRenderer.cs

or you can use updated version on NuGet

**Comment by Elfobog** [comment]
Thank you so much!

**Comment by Elfobog** [comment]
I have this error with a new version:
1 error XA2002: Can not resolve reference: `FFImageLoading.Forms.Platform`, referenced by `Plugin.XF.Controls.Droid`. Please add a NuGet package or assembly reference for `FFImageLoading.Forms.Platform`, or remove the reference to `Plugin.XF.Controls.Droid`.

2)error XA2002: Can not resolve reference: `FFImageLoading.Forms`, referenced by `Plugin.XF.Controls.Shared`. Please add a NuGet package or assembly reference for `FFImageLoading.Forms`, or remove the reference to `Plugin.XF.Controls.Shared`.

**Comment by JimmyPun610** [comment]
Hi @Elfobog 

I forgot to add FFImage package to NuGet.
Fixed in 1.0.11
